version: "3.3"
services:
  db-compose:
    container_name: db-compose
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dbo
    ports:
      - 5432:5432

  gomoku-service:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile-spring
    environment:
      PORT: 8080
      DATABASE_URL: "jdbc:postgresql://db-compose:5432/dbo?user=postgres&password=postgres"

  nginx:
    container_name: nginx
    build:
      context: ..
      dockerfile: ./jvm/dockerfiles/Dockerfile-nginx
    ports:
      - 8080:8080
    depends_on:
      - gomoku-service

  ubuntu:
    container_name: ubuntu
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile-ubuntu
    tty: true